# Generated by Django 4.2 on 2023-05-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=50)),
                ('re_password', models.CharField(max_length=50)),
                ('laptop', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('about', models.CharField(max_length=50)),
                ('text_area', models.CharField(max_length=50)),
                ('check_box', models.CharField(max_length=50)),
                ('files', models.CharField(max_length=50)),
            ],
        ),
    ]
