# Generated by Django 4.2 on 2023-06-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('exam', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='question_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
